### ISSUE TITLE
Implement governance v0.1 spec

### ISSUE THREAD

**Issue by shahankhatch** [windranger-io/windranger-governance#1]
Follow 0.1 spec that's been specced out here:
https://github.com/bitdao-io/governance/blob/main/docs/Architecture.md

- [x] Specification
- [x] Dao
- [x] Proposal with list of (role-based) actions
- [x] Protocols
- [x] Parent and child dao mapping
- [x] Actions
- [x] Treasury
- [x] Parent-child treasury mapping
- [x] Roles (mixin with [OZ Access contracts](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/access)
- [x] Delegation to roles
- [x] Role-to-allowed-actions mapping
- [x] Role-based voting strategies, e.g., veto for owners, super majority for monitors
- [x] Role-based action example, e.g., only board member votes can create a new treasury
- [x] Proposal verification
- [x] Integration with Snapshot
- [x] Example instance of a dao, i.e., simplified example of Pentagon, Juicebox, Szns, Sharkdao
- [x] Tests
- [x] Documentation

**Comment by bitparadigm** [comment]
Overall, I suppose all boxes are ticked now so we can close this issue. If smth is missing we can open tickets separately closer to when we will need roles based Governance and our special GovernorBravo.
