### ISSUE TITLE
[Feature] Add proxies into repo and test flows with them

### ISSUE THREAD

**Issue by bitparadigm** [windranger-io/windranger-governance#58]
## Feature Description
1. Research details about https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/proxy
2. Add TransparentUpgradabilityProxy and ProxyAdmin into repo
3. Add proxies into tests and scripts to test upgrades flows and functionality in general.

**Comment by CjHare** [comment]
What is the motivation for choosing the Transparent proxy over the UUPS proxy?
